version: '3'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.10
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 8090:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://10.10.10.185:8090"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "tranamnhdat@protonmail.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "56Aenvmkasfurqwi49^#masfj"
      # Setup the database connection. "teedy-db" is the hostname
      # and "teedy" is the name of the database the application
      # will connect to.
      DATABASE_URL: "jdbc:postgresql://teedy-db:5432/teedy"
      DATABASE_USER: "komodoteam"
      DATABASE_PASSWORD: "45rtfgvb"
    volumes:
      - /mongodb_data/project/edms/docs_data/data:/data
    networks:
      - docker-internal
      - internet
    depends_on:
      - teedy-db

# DB for Teedy
  teedy-db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: "komodoteam"
      POSTGRES_PASSWORD: "45rtfgvb"
      POSTGRES_DB: "teedy"
    volumes:
      - /mongodb_data/project/edms/docs_data/db:/var/lib/postgresql/data
    networks:
      - docker-internal

networks:
  # Network without internet access. The db does not need
  # access to the host network.
  docker-internal:
    driver: bridge
    internal: true
  internet:
    driver: bridge